hw1 done
lllFaNToMlll/park_c_cpp_hw pull request #1
Opened 2021-10-11 15:46 UTC by lllFaNToMlll

Вариант #3
Создать структуру для хранения информации о погодных условиях: температуре, осадках, скорости ветра. Составить с ее использованием программу расчета средней, минимальной и максимальной температуры и количества осадков, выпавших за неделю. Для возврата полученной информации также используйте созданную для этих целей структуру данных.

2021-10-11 23:52 UTC, ThCompiler commented on WeatherInputOutput.c
> +        weekWeather[i].temperature = atof(userInput);
3 раза повторяющееся логика, можно вынести в отдельную функцию

2021-10-11 23:52 UTC, ThCompiler commented on WeatherInputOutput.c
> +        while (atof(userInput) > MAX_TEMPERATURE || atof(userInput) < MIN_TEMPERATURE || atof(userInput) == 0){
А температура не может быть 0 градусов? И не хватает обработки возвращаемого значения `scanf`. Что будет если пользователь прекратит ввод? Это тоже надо обработать. В `scanf` можно напрямую читать числа:
> int res = scanf("%f", &userInput)

И дальше нужно проверить результат функции и можно работать со считанным значением.

2021-10-11 23:52 UTC, ThCompiler commented on Weather.h
> +weatherInfo *createWeek(weatherInfo weekWeather[]);
Не очень понятно на что возвращается указатель, без просмотра конкретной реализации, это может быть и указатель на структуру и указатель на начала массива. И зачем нужно передавать на вход уже какой-то массив

2021-10-11 23:52 UTC, ThCompiler commented on WeatherInputOutput.c
> +    for (int i = 0; i < SIZE; ++i) {
Интересный способ уклониться от динамического выделения памяти. Не знаю как сейчас, но у нас к тому описанию был ещё абзац, где сказано, что число элементов в массиве произвольное, а значит его нельзя задать статическим массивом. У такой штуки с SIZE есть ещё проблема связности кода, если где-то ошибиться с использованием этого параметра, то могут пострадать все кто работает на основе SIZE

2021-10-11 23:52 UTC, ThCompiler commented on WeatherInputOutput.c
> +        scanf("%s", userInput);
Вообще выгодней использовать не просто чтение и запись в стандартный ввод-вывод, а передавать в эту функцию `FILE*`, из которого читать через `fscanf`. Это некоторая унификация позволяющая не писать лишний код если поменяется интерфейс взаимодействия с пользователем. Аналогично для функций вывода структур

2021-10-11 23:52 UTC, ThCompiler commented on Weather.h
> +#define MIN_WINDSPEED 0
Дефайны желательно спрятать в сорцы, чтобы не показывать особенности реализации прототипов функции. И обычно такие дефайны ставятся после инклудов, самый верхний он просто нужен для других целей.

2021-10-12 11:15 UTC, lllFaNToMlll commented on Weather.h
> +#define MIN_WINDSPEED 0
Но у меня они используются в трех файлах. Нужно их дублировать в каждом? Разве так красиво выйдет?

2021-10-17 21:28 UTC, a-badin requested changes
Вы можете зафискировать длину массива в 7 дней, так чтобы длина "была видна" в функциях, если завернете `weatherInfo  weatherWeek[SIZE]` в структуру и вместо const weatherInfo [] будете передавать эту структуру

2021-10-17 21:28 UTC, a-badin commented on WeatherInputOutput.c
> +            checkSize(size);
checkSize делается 2 раза после выхода из цикла while, замените break на return

2021-10-17 21:28 UTC, a-badin commented on WeatherInputOutput.c
> +            weekWeather[i].temperature = buf;
Так как из if вы выходите через break/return, то else не нужен

2021-10-17 21:28 UTC, a-badin commented on WeatherInputOutput.c
> +    int scanChecker = 0, i = 0, buf = 0, size = 0;
Кажется buf  лишний, выможете сразу писать в структуры как делаете это с другими полями

2021-10-17 21:28 UTC, a-badin commented on WeatherInputOutput.c
> +        i++;
Кажется i у вас совпадет с size всегда

2021-10-17 21:28 UTC, a-badin commented on WeatherInputOutput.c
> +        if (i == 7) {
Замените while на for, вы итерируете по size от 0 до 7

2021-10-17 21:28 UTC, a-badin commented on WeatherInputOutput.c
> +#define MAX_TEMPERATURE 75
У вас повторяются константы, объявите их в отдельном h файле, и подключайте где надо

2021-10-17 21:28 UTC, a-badin commented on Weather.c
> +    weatherAnalysis analysisData = {0, 0, 0};
В weatherAnalysis  4 поля, значит 1 осталось не проиницилиазировано

2021-10-17 21:28 UTC, a-badin commented on Weather.c
> +    analysisData.maxTemperature = MIN_TEMPERATURE;
Зачем инициализировать поля нулем строчкой выше, чтобы сразу поменять его на другое значение

2021-10-17 21:28 UTC, a-badin commented on Weather.c
> +    analysisData.minTemperature = MAX_TEMPERATURE;
А как быть, если бы температура была неограничена? Если проинициализовать все поля значениями, например, первого дня, то проблем не будет

2021-10-17 21:28 UTC, a-badin commented on Weather.h
> +typedef struct weatherInfo {
Вы можете не давать структуре имя, если сразу делаете ей typedef

2021-10-17 21:28 UTC, a-badin commented on Weather.h
> +void printAnalysis(const weatherAnalysis analysisWeek);
У вас копируется структура за зря

2021-10-17 21:28 UTC, a-badin commented on test_weather.cpp
> +int main(int argc, char** argv) {
Если линковать с GTest::gtest_main или в старых версиях GTest::Main, то писать int main в тестах будет не нужно

2021-10-19 11:09 UTC, lllFaNToMlll commented on WeatherInputOutput.c
> +                      const int min, const int max, int *scanChecker) {
согласен, но не смог придумать, как изменить в таком случае мой алгоритм

2021-10-19 11:10 UTC, lllFaNToMlll commented on WeatherInputOutput.c
> +double checkUserInput(const char string[], const int index,
Согласен, что это правильнее, но не смог придумать, как в этом случае возвращать сам ввод пользователя.

2021-11-02 09:13 UTC, merged